# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.2]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: npm install
      run: |
        npm install

    - name: EAS build
      run: |
        npx eas build --platform android --profile production --non-interactive --no-publish --local --verbose
          
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: ./*.apk
        